version: "3.7"

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file: ./.env
    ports:
      - 5432:5432
  web:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    command: >
      bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
